<?php

namespace SolubleTest\Datatype\Column;

use Soluble\Datatype\Column\Type;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-04 at 13:55:32.
 */
class TypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    public function testGetSupportedTypes()
    {
        $supported = Type::getSupportedTypes();
        $this->assertInternalType('array', $supported);
    }

    public function testCreateColumnDefinition()
    {
        $columnDef = Type::createColumnDefinition(Type::TYPE_INTEGER, 'flag_one', 'table1', 'schema1');
        $this->assertInstanceOf('\Soluble\DataType\Column\Definition\AbstractColumnDefinition', $columnDef);
        $this->assertInstanceOf('\Soluble\DataType\Column\Definition\IntegerColumn', $columnDef);
        $this->assertEquals('flag_one', $columnDef->getName());
        $this->assertEquals('table1', $columnDef->getTableName());
        $this->assertEquals('schema1', $columnDef->getSchemaName());
    }

    public function testCreateColumnDefinitionThrowsException()
    {

        $this->setExpectedException('Soluble\Datatype\Exception\UnsupportedTypeException');
        $columnDef = Type::createColumnDefinition('invalid_type', 'flag_one');
    }
}
